export const Command = {
  TabPrevious: 'tab-previous',
  TabNext: 'tab-next',
  TabMoveToPrevious: 'tab-move-to-previous',
  TabMoveToNext: 'tab-move-to-next',
  TabMoveToFirst: 'tab-move-to-first',
  TabMoveToLast: 'tab-move-to-last',
  TabReload: 'tab-reload',
  TabDuplicate: 'tab-duplicate',
  TabPin: 'tab-pin',
  TabMute: 'tab-mute',
  TabClose: 'tab-close',
  TabCreateNew: 'tab-create-new',
  TabGoBack: 'tab-go-back',
  TabGoForward: 'tab-go-forward',
  TabNewInGroup: 'tab-new-in-group',
  WindowNew: 'window-new',
  WindowNewIncognito: 'window-new-incognito',
  OpenExtensions: 'open-extensions',
  OpenExtensionsShortcuts: 'open-extensions-shortcuts',
  OpenDownloads: 'open-downloads',
  OpenSettings: 'open-settings',
  OpenHistory: 'open-history',
  OpenBookmarks: 'open-bookmarks',
  OpenHelp: 'open-help',
  OpenFlags: 'open-flags',
};
